# Generated by Django 2.2.3 on 2019-08-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190731_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_image',
        ),
    ]
