# Generated by Django 2.2.3 on 2019-08-07 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190808_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply_to',
            new_name='parent',
        ),
    ]
