# Generated by Django 2.2.3 on 2019-09-28 06:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190808_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='model_pic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
