# Generated by Django 2.2.3 on 2019-10-07 17:13

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190928_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=martor.models.MartorField(blank=True, null=True, verbose_name='İçerik'),
        ),
    ]
